const CREATE_DB_JOKES = 'CREATE DATABASE IF NOT EXISTS jokes'

const USE_DB_JOKES = 'USE jokes'

const CREATE_TABLE_JOKES = `CREATE TEMPORARY TABLE jokes (
  id INT AUTO_INCREMENT PRIMARY KEY, 
  setup VARCHAR(120) NOT NULL, 
  punchline VARCHAR(120) NOT NULL
)`

const INSERT_MANY_JOKES = `INSERT INTO jokes (setup, punchline) VALUES ?`

const SELECT_RANDOM_JOKE = ` SELECT * FROM jokes
  ORDER BY RAND()
  LIMIT 1;
`

module.exports = {
  CREATE_DB_JOKES,
  USE_DB_JOKES,
  CREATE_TABLE_JOKES,
  INSERT_MANY_JOKES,
  SELECT_RANDOM_JOKE
}
